contigua:
	# Compilando a implementacao da fila
	gcc -c fila_contigua.c -o fila_contigua.o
	
	# Compilando e gerando o executavel
	gcc main.c fila_contigua.o -o main_filaContigua
	
	# Executando
	./main_filaContigua	

encadeada:
	# Compilando a implementacao da fila
	gcc -c fila_encadeada.c -o fila_encadeada.o
	
	# Compilando e gerando o executavel
	gcc main.c fila_encadeada.o -o main_filaEncadeada
	
	# Executando
	./main_filaEncadeada

clean:
	rm *.o
	rm main_filaContigua
	rm main_filaEncadeada


atividade01:

	# Compilando a implementacao da fila
	gcc -c fila_contigua.c -o fila_contigua.o
	
	# Compilando e gerando o executavel
	gcc atividade01.c fila_contigua.o -o atividade01
	
	# Executando
	./atividade01

	rm atividade01

atividade02:
	# Compilando a implementacao da fila
	gcc -c fila_contigua.c -o fila_contigua.o

	gcc -c pilha_contigua.c -o pilha_contigua.o
	
	# Compilando e gerando o executavel
	gcc atividade02.c fila_contigua.o pilha_contigua.o -o atividade02
	
	# Executando
	./atividade02

	rm atividade02

atividade03:
	# Compilando a implementacao da fila
	gcc -c fila_contigua.c -o fila_contigua.o

	gcc -c pilha_contigua.c -o pilha_contigua.o
	
	# Compilando e gerando o executavel
	gcc atividade03.c fila_contigua.o pilha_contigua.o -o atividade03
		
	# Executando
	./atividade03

	rm atividade03	


atividade04:
	# Compilando a implementacao da fila
	gcc -c fila_contigua.c -o fila_contigua.o
	
	# Compilando e gerando o executavel
	gcc atividade04.c fila_contigua.o -o atividade04
	
	# Executando
	./atividade04

	rm atividade04	

atividade05:
	# Compilando a implementacao da fila
	gcc -c fila_contigua.c -o fila_contigua.o
	
	# Compilando e gerando o executavel
	gcc atividade05.c fila_contigua.o -o atividade05
	
	# Executando
	./atividade05		

	rm atividade05

atividade06:
	# Compilando a implementacao da fila
	gcc -c fila_contigua.c -o fila_contigua.o
	
	# Compilando e gerando o executavel
	gcc atividade06.c fila_contigua.o -o atividade06
	
	# Executando
	./atividade06

	rm atividade06		