contigua:
	gcc -c pilha_contigua.c -o pilha_contigua.o
	gcc main.c pilha_contigua.o -o main_pilhaContigua
	./main_pilhaContigua

contigua_01:
	gcc -c pilha_contigua.c -o pilha_contigua.o
	gcc atividade01.c pilha_contigua.o -o atividade01
	./atividade01	

contigua_02:
	gcc -c pilha_contigua.c -o pilha_contigua.o
	gcc atividade02.c pilha_contigua.o -o atividade02
	./atividade02

contigua_03:
	gcc -c pilha_contigua.c -o pilha_contigua.o
	gcc atividade03.c pilha_contigua.o -o atividade03
	./atividade03

contigua_04:
	gcc -c pilha_contigua.c -o pilha_contigua.o
	gcc atividade04.c pilha_contigua.o -o atividade04
	./atividade04	

encadeada:
	gcc -c pilha_encadeada.c -o pilha_encadeada.o
	gcc main.c pilha_encadeada.o -o main_pilhaEncadeada
	./main_pilhaEncadeada

clean:
	rm *.o
	rm main_pilhaContigua
	rm main_pilhaEncadeada