CountPositive:
	javac CountPositive.java
	java CountPositive

FindLast:
	javac FindLast.java
	java FindLast

LastZero:
	javac LastZero.java
	java LastZero

OddOrPos:
	javac OddOrPos.java
	java OddOrPos

Triangulo:
	javac Triangulo.java
	java Triangulo